### ISSUE TITLE
How to limit form submission

### ISSUE THREAD

**Issue by RomainCscn** [danielireson/formplug-serverless#13]
Hello, 

First, thank you for your project, it works great!

I was wondering, apart from the honeypot, did you think of any way to limit form submission (based on IP for example)?

Thanks again.

**Comment by danielireson** [comment]
The latest latest release adds support for [reCaptcha v3](https://github.com/danielireson/formplug-serverless/releases/tag/1.2.0) which can be used to prevent spam submissions, hopefully you'll find that useful.

Restricting form submissions to certain IP address ranges could be a good idea, although it might be difficult to build up a comprehensive whitelist/blacklist and keep it updated.

I'm going to close the issue but feel free to reopen if your use case wouldn't be resolved by reCaptcha v3 support.
