### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by grantballmer** [danielireson/formplug-serverless#14]
I think I'm a little confused. I've installed Serverless and setup my AWS credentials with it. Now I'm at npm install dependencies. Am I supposed to clone/copy the whole formplug-serverless repository into my project?

**Comment by danielireson** [comment]
Hi Grant, this service would typically be deployed independently to your existing project so I would not copy it into your existing repository. Your existing project would interact with formplug via the URL that you receive after deploying.
