### ISSUE TITLE
Multiple Email Addresses

### ISSUE THREAD

**Issue by azath** [danielireson/formplug-serverless#2]
Hi. Thanks for this great plugin, as well as the recent write-up explaining how it works!

I've been working on taking down some old drupal sites into HTML as they are no longer supported, and many may be easily hosted on S3. The problem with this is the contact form functionality, which formplug resolves very easily, compared to other more involved lambda setups. 

However, some of our contact forms send to multiple email addresses. Is there a way to post a string of email addresses, or any plans to implement this feature? 

Either way, much gratitude.

**Comment by danielireson** [comment]
Hi Azath, great to hear you find the service useful. I actually have been meaning to add support for multiple email addresses - the need for it also came up in one of my projects. I'll probably release an update later in the week, i'll let you know when I do.

**Comment by danielireson** [comment]
Hi Azath, I've just pushed up an update to support cc email addresses. Have a look and let me know if you have any problems.

**Comment by azath** [comment]
Thanks so much Daniel!
This seems to work very well. 

I noticed that encrypted emails in the _cc input aren't working for me. 
Encryption in cc would be nice, but I'll take what I can get!

**Comment by danielireson** [comment]
No worries. Yes I unfortunately didn't add encryption support to cc as i'm a bit short on time at the moment. I'll probably add it at some point in the future though, although it shouldn't be too hard to do if you want to have a go and make a pull request. Should just be a small change to _handlers/receive/request.js_.

**Comment by danielireson** [comment]
Hi Azath, the most recent release on master includes the functionality to encrypt CC emails. The project has also undergone a complete restructure with some breaking changes, so be sure to check the readme.
