### ISSUE TITLE
Feature Request: Support for ReplyToAddress

### ISSUE THREAD

**Issue by viraf** [danielireson/formplug-serverless#5]
Allow to set ReplyToAddress of the contact form to email address field in the form.

**Comment by danielireson** [comment]
Hi Viraf, please see the most recent release on master which includes the functionality to set reply to addresses. I undertook a complete rewrite to make the project easier to update in the future, but this unfortunately included breaking changes, so check the readme before you update. Let me know if you run into any issues.

**Comment by viraf** [comment]
Thanks will check.
